name: MapArtLock
version: '${version}'

main: nl.chimpgamer.mapartlock.MapArtLockPlugin
api-version: '1.21'
load: POSTWORLD

authors: [ ChimpGamer, HetGoed ]
description: Protect filled map art from duplication and unwanted edits.

permissions:
  mapart.*:
    description: "Userrechten: /mapart openen, right-click GUI openen en eigen mapart locken/unlocken."
    default: false
  mapart.admin:
    description: "Adminrechten: andermans mapart locken/unlocken en /mapart version plus /mapart reload gebruiken."
    default: op
    children:
      mapart.*: true
